/**
 * Generates the committed artifacts from the Zod schemas:
 *   schema/homerun.schema.json   JSON Schema bundle ($defs per named schema)
 *   schema/callers.json          per-caller method allowlists
 *   schema/manifest.json         versions, event types, method → schema names
 *   vectors/<group>.json         golden vectors
 *   vectors/answer-rules.json    golden cases for checkResponse (who may answer what)
 *
 *   bun run scripts/gen.ts           write
 *   bun run scripts/gen.ts --check   fail if anything differs from what is committed
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { buildCallers, buildManifest, buildSchemaBundle } from "../src/index";
import { VECTOR_GROUPS } from "./vectors/index";
import { answerRules } from "./vectors/answer-rules";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

export function generate(): Map<string, string> {
  const files = new Map<string, string>();
  const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
  files.set("schema/homerun.schema.json", json(buildSchemaBundle()));
  files.set("schema/callers.json", json(buildCallers()));
  files.set("schema/manifest.json", json(buildManifest()));
  for (const [group, cases] of Object.entries(VECTOR_GROUPS)) {
    files.set(
      `vectors/${group}.json`,
      json({
        $comment: "Generated by packages/core/scripts/gen.ts from scripts/vectors. `schema` names a $defs entry of schema/homerun.schema.json.",
        cases: JSON.parse(JSON.stringify(cases)),
      }),
    );
  }
  files.set(
    "vectors/answer-rules.json",
    json({
      $comment:
        "Generated by packages/core/scripts/gen.ts from scripts/vectors/answer-rules.ts. `allowed` says whether the runtime accepts `response` to `prompt` from `from.role` via `from.via` (checkResponse).",
      cases: JSON.parse(JSON.stringify(answerRules)),
    }),
  );
  return files;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const stale: string[] = [];
  for (const [path, content] of generate()) {
    const abs = join(ROOT, path);
    const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
    if (current === content) continue;
    if (check) stale.push(relative(process.cwd(), abs));
    else {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content);
      console.log(`wrote ${path}`);
    }
  }
  if (stale.length > 0) {
    console.error(`Generated files are out of date. Run \`pnpm --filter @homerun/core gen\` and commit:\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  if (check) console.log("schema and vectors are up to date");
}
