import { z } from "zod";
import { named } from "./registry";

// ---------------------------------------------------------------- identifiers

/** Lowercase canonical UUID (any version). Homerun-generated ids use UUIDv4 or v7. */
export const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export const DeviceId = named("DeviceId", z.string().regex(UUID_PATTERN).brand<"DeviceId">(), "One install, one OS user (§12)");
export type DeviceId = z.infer<typeof DeviceId>;
export const TaskId = named("TaskId", z.string().regex(UUID_PATTERN).brand<"TaskId">());
export type TaskId = z.infer<typeof TaskId>;
export const ThreadId = named("ThreadId", z.string().regex(UUID_PATTERN).brand<"ThreadId">());
export type ThreadId = z.infer<typeof ThreadId>;
export const RunId = named("RunId", z.string().regex(UUID_PATTERN).brand<"RunId">());
export type RunId = z.infer<typeof RunId>;
export const RequestId = named("RequestId", z.string().regex(UUID_PATTERN).brand<"RequestId">(), "An input request (§5.6)");
export type RequestId = z.infer<typeof RequestId>;
export const GrantId = named("GrantId", z.string().regex(UUID_PATTERN).brand<"GrantId">());
export type GrantId = z.infer<typeof GrantId>;
export const ScheduleId = named("ScheduleId", z.string().regex(UUID_PATTERN).brand<"ScheduleId">());
export type ScheduleId = z.infer<typeof ScheduleId>;
export const ClientMsgId = named(
  "ClientMsgId",
  z.string().regex(UUID_PATTERN).brand<"ClientMsgId">(),
  "Generated by the sending client; makes messages.send and queued instructions idempotent",
);
export type ClientMsgId = z.infer<typeof ClientMsgId>;

const opaque = z.string().min(1).max(256);
export const ToolCallId = named("ToolCallId", opaque.brand<"ToolCallId">(), "The SDK's tool_use id; opaque");
export type ToolCallId = z.infer<typeof ToolCallId>;
export const SdkSessionId = named("SdkSessionId", opaque.brand<"SdkSessionId">(), "Claude Agent SDK session id; opaque");
export type SdkSessionId = z.infer<typeof SdkSessionId>;
export const MessageId = named("MessageId", opaque.brand<"MessageId">(), "Assistant message id from the SDK; ties deltas to their final message");
export type MessageId = z.infer<typeof MessageId>;

// ---------------------------------------------------------------- scalars

export const TimestampMs = named("TimestampMs", z.int().nonnegative(), "Milliseconds since the Unix epoch, UTC");
export type TimestampMs = z.infer<typeof TimestampMs>;

/** Per-thread event sequence number. The first event of a thread has seq 1. */
export const Seq = named("Seq", z.int().min(1));
export type Seq = z.infer<typeof Seq>;

export const Sha256Hex = named("Sha256Hex", z.string().regex(/^[0-9a-f]{64}$/));

export const Base64Url = z.string().regex(/^[A-Za-z0-9_-]*$/);

export const JsonValue = named("JsonValue", z.json());
export type JsonValue = z.infer<typeof JsonValue>;

export const Surface = named(
  "Surface",
  z.enum(["desktop", "cli", "ios", "web"]),
  "Where a message or answer was sent from. Only 'web' has reduced authority (§9.9)",
);
export type Surface = z.infer<typeof Surface>;

export const Origin = named(
  "Origin",
  z.object({ device_id: DeviceId, surface: Surface }),
  "The authenticated device that sent something (§9.9), never taken from message content",
);
export type Origin = z.infer<typeof Origin>;

// ---------------------------------------------------------------- sizes

/** UTF-8 byte length without relying on TextEncoder (not in the ES lib). */
export function utf8ByteLength(s: string): number {
  let n = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c < 0x80) n += 1;
    else if (c < 0x800) n += 2;
    else if (c >= 0xd800 && c <= 0xdbff && i + 1 < s.length) {
      const d = s.charCodeAt(i + 1);
      if (d >= 0xdc00 && d <= 0xdfff) {
        n += 4;
        i++;
      } else n += 3;
    } else n += 3;
  }
  return n;
}

export function jsonByteLength(v: unknown): number {
  return utf8ByteLength(JSON.stringify(v) ?? "");
}

/** Monitor state and check results are capped at 64 KB of serialized JSON (§8.3). */
export const MONITOR_STATE_MAX_BYTES = 64 * 1024;
/** Tool inputs and outputs above this are moved to `blobs` (§6.1). */
export const BLOB_INLINE_MAX_BYTES = 4 * 1024;
export const BLOB_PREVIEW_MAX_CHARS = 500;

// ---------------------------------------------------------------- blobs (§6.1)

export const BlobRef = named(
  "BlobRef",
  z.object({
    kind: z.literal("blob"),
    sha256: Sha256Hex,
    size: z.int().nonnegative(),
    preview: z.string().max(BLOB_PREVIEW_MAX_CHARS),
    /** Set once retention has deleted the bytes. The event keeps hash, size and preview. */
    expired: z.boolean(),
  }),
);
export type BlobRef = z.infer<typeof BlobRef>;

export const InlineContent = named(
  "InlineContent",
  z.object({ kind: z.literal("inline"), value: JsonValue }).refine((c) => jsonByteLength(c.value) <= BLOB_INLINE_MAX_BYTES, {
    message: `inline content over ${BLOB_INLINE_MAX_BYTES} bytes must be a blob`,
    path: ["value"],
  }),
);

/** A tool input or output: inline when small, otherwise a reference into `blobs`. */
export const Content = named("Content", z.discriminatedUnion("kind", [InlineContent, BlobRef]));
export type Content = z.infer<typeof Content>;

export function assertNever(x: never, what = "value"): never {
  throw new Error(`unhandled ${what}: ${JSON.stringify(x)}`);
}
