import { CLOCK_SKEW_MS, type SealedInner } from "@homerun/core";
import { framed, fromB64url, fromHex, toB64url, toHex, utf8 } from "../bytes";
import { x25519Key } from "../crypto";
import { buildApnsPayload } from "../apns";
import { LinkInitiator, LinkResponder, sasCommit, sasCode } from "../linking";
import { LiveInitiator, livePrologue, liveRespond } from "../live";
import { HandshakeState } from "../noise";
import { decodePairingUrl, encodePairingUrl, offerTag, pairingPsk, PairInitiator, PairResponder } from "../pairing";
import { openSealed, seal, sealRaw, type SealedEnvelope, type SealedHeader } from "../sealed";
import { linkStatementBytes, signLinkStatement, type LinkStatementBody } from "../statement";
import { challengeBytes, requestBytes, signChallenge, signRequest } from "../wire";
import { p256 } from "@noble/curves/nist.js";
import { attestationClientDataHash, IOS_APP_ID } from "../app-attest";
import { testAppAttestCA, testAssertion } from "../testing/app-attest";
import { ACCOUNT, identityOf, T0, vectorDeviceKeys, type VectorDeviceName } from "./fixtures";
import { seededRandom } from "./seeded";

/**
 * Builds the contents of every vector file from fixed seeds. `scripts/gen-vectors.ts` writes them;
 * `verify.ts` checks an implementation against them using only what the files contain.
 */

const HOUR = 60 * 60 * 1000;
const keys = (n: VectorDeviceName) => vectorDeviceKeys(n);
const id = (n: VectorDeviceName) => identityOf(keys(n), fromHex);
const eph = (label: string) => x25519Key(seededRandom(`ephemeral/${label}`)(32));
const msgId = (label: string) => toB64url(seededRandom(`msg/${label}`)(16));
const session = (label: string) => toB64url(seededRandom(`session/${label}`)(16));

const COMMENT = (file: string) =>
  `Generated by packages/protocol/scripts/gen-vectors.ts; see packages/protocol/README.md for the format. Test keys only. ${file}`;

// ---------------------------------------------------------------- sealed

export async function buildSealed() {
  const phone = id("phone");
  const desktop = id("desktop");
  const other = id("other");
  const seals: Record<string, unknown>[] = [];
  const opens: Record<string, unknown>[] = [];

  const inner = (label: string, body: SealedInner["body"], created = T0, lifetime = HOUR, sender = phone.deviceId): SealedInner =>
    ({ v: 1, msg_id: msgId(label), sender_device_id: sender, created_at: created, expires_at: created + lifetime, body }) as SealedInner;

  const instruction = inner("instruction", {
    type: "instruction",
    thread_id: null,
    client_msg_id: "7f3e2d1c-0b9a-4876-9543-210fedcba987",
    text: "Summarise the open pull requests in homerun and draft replies.",
  } as SealedInner["body"], T0, 12 * HOUR);
  const push = inner(
    "push",
    {
      type: "push",
      category: "input_request",
      title: "Approval needed",
      body: "The agent wants to run `npm install` in homerun.",
      thread_id: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
      request_id: "4c3b2a19-0f8e-4d7c-9b6a-5f4e3d2c1b0a",
      actions: [
        { id: "allow", label: "Allow" },
        { id: "deny", label: "Deny" },
      ],
    } as SealedInner["body"],
    T0,
    24 * HOUR,
    desktop.deviceId,
  );
  const answer = inner("answer", {
    type: "answer",
    request_id: "4c3b2a19-0f8e-4d7c-9b6a-5f4e3d2c1b0a",
    response: { type: "approval", decision: "allow" },
    via: "notification",
  } as SealedInner["body"]);
  const long = inner("long", {
    type: "instruction",
    thread_id: null,
    client_msg_id: "7f3e2d1c-0b9a-4876-9543-210fedcba988",
    text: "A longer instruction that is split into several fragments. ".repeat(4),
  } as SealedInner["body"], T0, 12 * HOUR);

  const add = async (name: string, o: { inner: SealedInner; from: typeof phone; to: typeof desktop; toStatic?: Uint8Array; maxChunk?: number }) => {
    const e = eph(`sealed/${name}`);
    const env = await seal({ inner: o.inner, to: o.to.deviceId, sender: o.from.noise, recipientStatic: o.toStatic ?? o.to.noise.publicKey, e, maxChunk: o.maxChunk });
    seals.push({
      name,
      sender: o.from === phone ? "phone" : "desktop",
      recipient_static: toB64url(o.toStatic ?? o.to.noise.publicKey),
      to_device_id: o.to.deviceId,
      ephemeral_secret: toHex(e.secretKey),
      max_chunk: o.maxChunk ?? null,
      inner: o.inner,
      envelope: env,
    });
    return env;
  };
  const addRaw = async (name: string, header: SealedHeader, plaintext: string) => {
    const e = eph(`sealed/${name}`);
    const env = await sealRaw({ header, plaintext: utf8(plaintext), sender: phone.noise, recipientStatic: desktop.noise.publicKey, e });
    seals.push({ name, sender: "phone", recipient_static: toB64url(desktop.noise.publicKey), ephemeral_secret: toHex(e.secretKey), header, plaintext, envelope: env });
    return env;
  };
  const open = async (
    name: string,
    envelope: unknown,
    expect: { ok: true } | { ok: false; reason: string },
    o: { recipient?: VectorDeviceName; pinned?: Record<string, VectorDeviceName>; now?: number; seen?: string[] } = {},
  ) => {
    const recipient = o.recipient ?? "desktop";
    const pinned = o.pinned ?? { [phone.deviceId]: "phone" };
    const now = o.now ?? T0 + 60_000;
    const r = await openSealed(envelope, {
      me: id(recipient),
      senderStatic: (d) => (pinned[d] ? id(pinned[d]!).noise.publicKey : null),
      now,
      seen: (m) => (o.seen ?? []).includes(m),
    });
    const got = r.ok ? { ok: true } : { ok: false, reason: r.reason };
    if (JSON.stringify(got) !== JSON.stringify(expect)) throw new Error(`vector ${name}: expected ${JSON.stringify(expect)}, got ${JSON.stringify(got)}`);
    opens.push({
      name,
      recipient,
      pinned: Object.fromEntries(Object.entries(pinned).map(([d, n]) => [d, keys(n).x25519_public])),
      now,
      seen: o.seen ?? [],
      envelope,
      expect: r.ok ? { ok: true, inner: r.inner } : expect,
    });
  };

  const envInstruction = await add("instruction", { inner: instruction, from: phone, to: desktop });
  const envPush = await add("push", { inner: push, from: desktop, to: phone });
  const envAnswer = await add("answer", { inner: answer, from: phone, to: desktop });
  const envLong = await add("fragmented", { inner: long, from: phone, to: desktop, maxChunk: 64 });
  const envWrongKey = await add("sealed to another key", { inner: answer, from: phone, to: desktop, toStatic: other.noise.publicKey });
  const future = inner("future", answer.body, T0 + CLOCK_SKEW_MS + 60_000);
  const envFuture = await add("from the future", { inner: future, from: phone, to: desktop });
  const tooLong = inner("too long", answer.body, T0, 2 * HOUR);
  const envTooLong = await add("lifetime too long", { inner: tooLong, from: phone, to: desktop });

  const lyingHeader = (label: string): SealedHeader => ({
    v: 1,
    mode: "sealed",
    kind: "answer",
    msg_id: msgId(label),
    to_device_id: desktop.deviceId,
    from_device_id: phone.deviceId,
    expires_at: T0 + HOUR,
  });
  const envSender = await addRaw("inner sender differs", lyingHeader("sender"), JSON.stringify({ ...answer, msg_id: msgId("sender"), sender_device_id: other.deviceId }));
  const envMsgId = await addRaw("inner msg_id differs", lyingHeader("msgid"), JSON.stringify({ ...answer, msg_id: msgId("different") }));
  const envNotJson = await addRaw("not JSON inside", lyingHeader("notjson"), "not json");

  await open("instruction opens", envInstruction, { ok: true });
  await open("push opens on the phone", envPush, { ok: true }, { recipient: "phone", pinned: { [desktop.deviceId]: "desktop" } });
  await open("answer opens", envAnswer, { ok: true });
  await open("fragmented instruction opens", envLong, { ok: true });
  await open("at the edge of the skew allowance", envAnswer, { ok: true }, { now: answer.expires_at + CLOCK_SKEW_MS });

  const flip = (env: SealedEnvelope, at: number): SealedEnvelope => {
    const b = fromB64url(env.ciphertext);
    b[at]! ^= 0x01;
    return { header: env.header, ciphertext: toB64url(b) };
  };
  await open("tampered ciphertext", flip(envInstruction, 60), { ok: false, reason: "decrypt_failed" });
  await open("tampered ephemeral key", flip(envInstruction, 3), { ok: false, reason: "decrypt_failed" });
  await open("tampered header: later expiry", { ...envAnswer, header: { ...envAnswer.header, expires_at: envAnswer.header.expires_at + HOUR } }, { ok: false, reason: "decrypt_failed" });
  await open("tampered header: kind", { ...envInstruction, header: { ...envInstruction.header, kind: "answer" } }, { ok: false, reason: "decrypt_failed" });
  await open("tampered header: msg_id", { ...envAnswer, header: { ...envAnswer.header, msg_id: msgId("swapped") } }, { ok: false, reason: "decrypt_failed" });
  await open("re-addressed to another device", { ...envAnswer, header: { ...envAnswer.header, to_device_id: other.deviceId } }, { ok: false, reason: "decrypt_failed" }, { recipient: "other" });
  await open("addressed to someone else", envAnswer, { ok: false, reason: "wrong_recipient" }, { recipient: "other" });
  await open("sealed to another key", envWrongKey, { ok: false, reason: "decrypt_failed" });
  await open("sender not paired", envAnswer, { ok: false, reason: "unknown_sender" }, { pinned: {} });
  await open("sender pinned with a different key", envAnswer, { ok: false, reason: "decrypt_failed" }, { pinned: { [phone.deviceId]: "other" } });
  await open("expired", envAnswer, { ok: false, reason: "expired" }, { now: answer.expires_at + CLOCK_SKEW_MS + 1 });
  await open("created in the future", envFuture, { ok: false, reason: "from_future" }, { now: T0 });
  await open("lifetime longer than the kind allows", envTooLong, { ok: false, reason: "lifetime_too_long" });
  await open("replayed", envAnswer, { ok: false, reason: "replayed" }, { seen: [answer.msg_id] });
  await open("inner sender differs from the header", envSender, { ok: false, reason: "sender_mismatch" });
  await open("inner msg_id differs from the header", envMsgId, { ok: false, reason: "header_mismatch" });
  await open("not JSON inside", envNotJson, { ok: false, reason: "malformed" });
  const truncated = (() => {
    const b = fromB64url(envLong.ciphertext);
    let off = 0;
    const starts: number[] = [];
    while (off < b.length) {
      starts.push(off);
      off += 2 + ((b[off]! << 8) | b[off + 1]!);
    }
    return { header: envLong.header, ciphertext: toB64url(b.subarray(0, starts[starts.length - 1])) };
  })();
  await open("last fragment dropped", truncated, { ok: false, reason: "malformed" });
  await open("unsupported version", { ...envAnswer, header: { ...envAnswer.header, v: 2 } }, { ok: false, reason: "unsupported_version" });
  await open("missing ciphertext", { header: envAnswer.header }, { ok: false, reason: "malformed" });

  return {
    $comment: COMMENT("Sealed messages (§9.4): `seal` cases must be reproduced byte for byte from their inputs; `open` cases must give `expect`."),
    devices: { desktop: keys("desktop"), phone: keys("phone"), other: keys("other") },
    clock_skew_ms: CLOCK_SKEW_MS,
    seal: seals,
    open: opens,
  };
}

// ---------------------------------------------------------------- live

export async function buildLive() {
  const phone = id("phone");
  const desktop = id("desktop");
  const sessionId = session("live");
  const ie = eph("live/initiator");
  const re = eph("live/responder");
  const common = { initiatorId: phone.deviceId, responderId: desktop.deviceId, sessionId, maxChunk: 48 };
  const init = new LiveInitiator({ ...common, me: phone.noise, peer: desktop.noise.publicKey, e: ie });
  const m1 = await init.start();
  const { reply: m2, session: dSession } = await liveRespond({ ...common, me: desktop.noise, peer: phone.noise.publicKey, e: re }, m1);
  const pSession = await init.finish(m2);
  const messages: Record<string, unknown>[] = [
    { from: "initiator", kind: "handshake", data: toB64url(m1) },
    { from: "responder", kind: "handshake", data: toB64url(m2) },
  ];
  const rpc = [
    { from: "initiator", msg: { jsonrpc: "2.0", id: 1, method: "hello", params: { protocol_versions: [1] } } },
    { from: "responder", msg: { jsonrpc: "2.0", id: 1, result: { protocol_version: 1 } } },
    { from: "initiator", msg: { jsonrpc: "2.0", id: 2, method: "threads.list", params: {} } },
  ];
  for (const r of rpc) {
    const s = r.from === "initiator" ? pSession : dSession;
    const frames = s.encrypt(r.msg as never);
    messages.push({ from: r.from, kind: "message", frames: frames.map(toB64url), plaintext: JSON.stringify(r.msg) });
  }
  // A first message made for another session id: the responder must refuse it.
  const otherInit = new LiveInitiator({ ...common, sessionId: session("live/other"), me: phone.noise, peer: desktop.noise.publicKey, e: eph("live/other") });
  return {
    $comment: COMMENT("Live sessions (§9.4): Noise_KK, prologue = framed(label, initiator id, responder id, session id); JSON-RPC messages in fragments of at most `max_chunk` bytes here."),
    devices: { initiator: keys("phone"), responder: keys("desktop") },
    session_id: sessionId,
    prologue: toHex(livePrologue(phone.deviceId, desktop.deviceId, sessionId)),
    initiator_ephemeral: toHex(ie.secretKey),
    responder_ephemeral: toHex(re.secretKey),
    max_chunk: 48,
    handshake_hash: toHex(pSession.handshakeHash),
    messages,
    reject: [
      { name: "first message for another session", data: toB64url(await otherInit.start()) },
      { name: "first message with a payload", data: toB64url(await firstWithPayload(phone, desktop, sessionId)) },
    ],
  };
}

function firstWithPayload(phone: ReturnType<typeof id>, desktop: ReturnType<typeof id>, sessionId: string): Promise<Uint8Array> {
  // Built directly on the handshake so the payload rule, not the prologue, is what fails.
  const hs = new HandshakeState({
    pattern: "KK",
    initiator: true,
    prologue: livePrologue(phone.deviceId, desktop.deviceId, sessionId),
    s: phone.noise,
    rs: desktop.noise.publicKey,
    e: eph("live/payload"),
  });
  return hs.writeMessage(utf8('{"jsonrpc":"2.0","id":9,"method":"tasks.run"}'));
}

// ---------------------------------------------------------------- statement

function statementBody(o: { platform: "ios" | "web"; method: "qr" | "code"; device: VectorDeviceName }): LinkStatementBody {
  return {
    v: 1,
    account: ACCOUNT,
    desktop_device_id: keys("desktop").device_id,
    device_id: keys(o.device).device_id,
    desktop_static_public_key: keys("desktop").x25519_public,
    device_static_public_key: keys(o.device).x25519_public,
    device_signing_public_key: keys(o.device).ed25519_public,
    platform: o.platform,
    method: o.method,
    created_at: T0,
  };
}

export async function buildStatements() {
  const desktop = id("desktop");
  const body = statementBody({ platform: "ios", method: "qr", device: "phone" });
  const signed = await signLinkStatement(body, desktop.signing);
  const webSigned = await signLinkStatement(statementBody({ platform: "web", method: "code", device: "web" }), desktop.signing);
  const otherSigner = await signLinkStatement(body, id("other").signing);
  return {
    $comment: COMMENT("Link statements (§10.5, §10.7): Ed25519 over `bytes`; `verify` cases give whether the statement verifies against `signer`."),
    devices: { desktop: keys("desktop"), phone: keys("phone"), web: keys("web"), other: keys("other") },
    sign: [
      { name: "ios by QR", body, bytes: toHex(linkStatementBytes(body)), statement: signed },
      { name: "web by code", body: statementBody({ platform: "web", method: "code", device: "web" }), bytes: toHex(linkStatementBytes(statementBody({ platform: "web", method: "code", device: "web" }))), statement: webSigned },
    ],
    verify: [
      { name: "valid", statement: signed, signer: keys("desktop").ed25519_public, valid: true },
      { name: "platform changed", statement: { ...signed, platform: "web" }, signer: keys("desktop").ed25519_public, valid: false },
      { name: "device key changed", statement: { ...signed, device_static_public_key: keys("other").x25519_public }, signer: keys("desktop").ed25519_public, valid: false },
      { name: "account changed", statement: { ...signed, account: "user_someone_else" }, signer: keys("desktop").ed25519_public, valid: false },
      { name: "signed by another device", statement: otherSigner, signer: keys("desktop").ed25519_public, valid: false },
      { name: "extra field", statement: { ...signed, admin: true }, signer: keys("desktop").ed25519_public, valid: false },
    ],
  };
}

// ---------------------------------------------------------------- pairing

export async function buildPairing() {
  const phone = id("phone");
  const desktop = id("desktop");
  const code = toB64url(seededRandom("pairing/code")(16));
  const qr = { v: 1 as const, device_id: desktop.deviceId, static_public_key: keys("desktop").x25519_public, pairing_code: code };
  const url = encodePairingUrl(qr as never);
  const sessionId = session("pair");
  const ie = eph("pair/initiator");
  const re = eph("pair/responder");
  const hello = { device_id: phone.deviceId, platform: "ios" as const, name: "Wenjing's iPhone", signing_public_key: keys("phone").ed25519_public };
  const init = new PairInitiator({ qr: decodePairingUrl(url)!, me: phone.noise, hello, sessionId, e: ie });
  const m1 = await init.start();
  const resp = new PairResponder({ desktopId: desktop.deviceId, deviceId: phone.deviceId, sessionId, code, me: desktop.noise, e: re });
  await resp.read(m1);
  const welcome = {
    device_id: desktop.deviceId,
    name: "Wenjing's MacBook Pro",
    signing_public_key: keys("desktop").ed25519_public,
    statement: await signLinkStatement(statementBody({ platform: "ios", method: "qr", device: "phone" }), desktop.signing),
  };
  const m2 = await resp.reply(welcome);
  await init.finish(m2);
  const wrong = new PairInitiator({
    qr: { ...decodePairingUrl(url)!, pairing_code: toB64url(seededRandom("pairing/wrong")(16)) },
    me: phone.noise,
    hello,
    sessionId,
    e: eph("pair/wrong"),
  });
  return {
    $comment: COMMENT("QR pairing (§9.6): Noise_IKpsk1, psk = HKDF-SHA256(code; salt = label; info = 'psk:' + desktop id)."),
    devices: { desktop: keys("desktop"), phone: keys("phone") },
    qr,
    url,
    psk: toHex(pairingPsk(code, desktop.deviceId)),
    offer_tag: offerTag(code),
    session_id: sessionId,
    initiator_ephemeral: toHex(ie.secretKey),
    responder_ephemeral: toHex(re.secretKey),
    hello,
    welcome,
    message1: toB64url(m1),
    message2: toB64url(m2),
    reject_message1: [{ name: "made with a different code", data: toB64url(await wrong.start()) }],
    urls: [
      { url, valid: true },
      { url: url.replace("homerun://pair", "homerun://evil"), valid: false },
      { url: "homerun://pair?d=bm90IGpzb24", valid: false },
      { url: `homerun://pair?d=${toB64url(utf8(JSON.stringify({ ...qr, pairing_code: "short" })))}`, valid: false },
    ],
  };
}

// ---------------------------------------------------------------- linking

export async function buildLinking() {
  const phone = id("phone");
  const desktop = id("desktop");
  const sessionId = session("link");
  const nP = seededRandom("link/nP")(32);
  const nD = seededRandom("link/nD")(32);
  const ie = eph("link/initiator");
  const re = eph("link/responder");
  const info = { device_id: phone.deviceId, platform: "ios" as const, name: "Wenjing's iPhone", signing_public_key: keys("phone").ed25519_public };
  const dinfo = { device_id: desktop.deviceId, name: "Wenjing's MacBook Pro", signing_public_key: keys("desktop").ed25519_public };
  const p = new LinkInitiator({ deviceId: phone.deviceId, desktopId: desktop.deviceId, sessionId, me: phone.noise, info, e: ie, nonce: nP });
  const d = new LinkResponder({ deviceId: phone.deviceId, desktopId: desktop.deviceId, sessionId, me: desktop.noise, info: dinfo, e: re, nonce: nD });
  const m1 = await p.start();
  const m2 = await d.accept(m1);
  const m3 = await p.answer(m2);
  const m4 = await d.commit(m3);
  const m5 = p.reveal(m4);
  const code = d.verify(m5);
  if (code !== p.code) throw new Error("codes differ");
  const statement = await signLinkStatement(statementBody({ platform: "ios", method: "code", device: "phone" }), desktop.signing);
  const m6 = d.linked(statement);
  p.result(m6);
  return {
    $comment: COMMENT("Linking with a matching code (§10.5): Noise_XX, then commit/reveal; code = 6 digits of SHA-256(label ‖ handshake hash ‖ nP ‖ nD), first 8 bytes big-endian mod 10^6."),
    devices: { desktop: keys("desktop"), phone: keys("phone") },
    session_id: sessionId,
    initiator_ephemeral: toHex(ie.secretKey),
    responder_ephemeral: toHex(re.secretKey),
    phone_nonce: toHex(nP),
    desktop_nonce: toHex(nD),
    commit: toB64url(sasCommit(nP)),
    code,
    phone_info: info,
    desktop_info: dinfo,
    statement,
    messages: [m1, m2, m3, m4, m5, m6].map(toB64url),
    codes: [
      { handshake_hash: "00".repeat(32), phone_nonce: "11".repeat(32), desktop_nonce: "22".repeat(32), code: sasCode(new Uint8Array(32), new Uint8Array(32).fill(0x11), new Uint8Array(32).fill(0x22)) },
      { handshake_hash: "ff".repeat(32), phone_nonce: "00".repeat(32), desktop_nonce: "00".repeat(32), code: sasCode(new Uint8Array(32).fill(0xff), new Uint8Array(32), new Uint8Array(32)) },
    ],
  };
}

// ---------------------------------------------------------------- APNs

export async function buildApns() {
  const desktop = id("desktop");
  const phone = id("phone");
  const base = {
    v: 1 as const,
    sender_device_id: desktop.deviceId,
    created_at: T0,
    expires_at: T0 + 24 * HOUR,
  };
  const pushOf = (label: string, title: string, body: string) =>
    seal({
      inner: { ...base, msg_id: msgId(`apns/${label}`), body: { type: "push", category: "run_finished", title, body } } as SealedInner,
      to: phone.deviceId,
      sender: desktop.noise,
      recipientStatic: phone.noise.publicKey,
      e: eph(`apns/${label}`),
    });
  const small = await pushOf("small", "Run finished", "Weekly report: done in 3 min.");
  const big = await pushOf("big", "Run finished", "🙂".repeat(1000));
  const cases = [
    { name: "fits", envelope: small },
    { name: "too big for 4 KB: generic text only", envelope: big },
  ].map((c) => ({ ...c, ...buildApnsPayload(c.envelope) }));
  return {
    $comment: COMMENT("APNs payloads (§9.7): at most 4,096 bytes; the sealed envelope rides in `hr` when it fits."),
    max_bytes: 4096,
    cases,
  };
}

// ---------------------------------------------------------------- relay wire and encoding

export async function buildWire() {
  const phone = id("phone");
  const nonce = toB64url(seededRandom("wire/nonce")(32));
  const body = JSON.stringify({ token: "ab".repeat(32), environment: "sandbox" });
  const ts = T0;
  return {
    $comment: COMMENT("Relay wire (§9.2–§9.5): device proofs and frame validity."),
    devices: { phone: keys("phone") },
    challenge: { nonce, device_id: phone.deviceId, bytes: toHex(challengeBytes(nonce, phone.deviceId)), signature: await signChallenge(phone.signing, nonce, phone.deviceId) },
    request: {
      device_id: phone.deviceId,
      ts,
      method: "POST",
      path: "/v1/push-token",
      body,
      bytes: toHex(requestBytes(phone.deviceId, ts, "POST", "/v1/push-token", utf8(body))),
      header: await signRequest(phone.signing, phone.deviceId, ts, "POST", "/v1/push-token", utf8(body)),
    },
    client_frames: [
      { frame: { type: "ping" }, valid: true },
      { frame: { type: "live", to: keys("desktop").device_id, session: session("wire"), data: "AAEC" }, valid: true },
      { frame: { type: "live", to: keys("desktop").device_id, session: "short", data: "AAEC" }, valid: false },
      { frame: { type: "live", to: keys("desktop").device_id, session: session("wire"), data: "not base64!" }, valid: false },
      { frame: { type: "ack", id: "q1", extra: 1 }, valid: false },
      { frame: { type: "unknown" }, valid: false },
      { frame: { type: "pair_open", offer: offerTag(toB64url(seededRandom("wire/code")(16))), expires_at: T0 + 300_000 }, valid: true },
    ],
    server_frames: [
      { frame: { type: "presence", device_id: keys("desktop").device_id, online: false, last_seen_at: T0 }, valid: true },
      { frame: { type: "receipt", msg_id: msgId("wire"), to: keys("desktop").device_id, status: "expired" }, valid: true },
      { frame: { type: "receipt", msg_id: msgId("wire"), to: keys("desktop").device_id, status: "lost" }, valid: false },
    ],
  };
}

export function buildEncoding() {
  return {
    $comment: COMMENT("base64url without padding (RFC 4648 §5), strict: `hex` null means the string must be refused."),
    base64url: [
      { hex: "", b64url: "" },
      { hex: "66", b64url: "Zg" },
      { hex: "666f", b64url: "Zm8" },
      { hex: "666f6f", b64url: "Zm9v" },
      { hex: "fbff", b64url: "-_8" },
      { hex: null, b64url: "Zg==" },
      { hex: null, b64url: "Zm9v+" },
      { hex: null, b64url: "Zh" },
      { hex: null, b64url: "Z" },
    ],
    framed: [{ parts: ["homerun", "", "ü"], hex: toHex(framed("homerun", "", "ü")) }],
  };
}

// ---------------------------------------------------------------- App Attest

export function buildAppAttest() {
  const who = (n: VectorDeviceName) => ({ device_id: keys(n).device_id, static_public_key: keys(n).x25519_public, signing_public_key: keys(n).ed25519_public });
  const approvalKey = toB64url(p256.getPublicKey(seededRandom("app-attest/approval")(32), false));
  const ca = testAppAttestCA("homerun-vector-app-attest");
  const phone = who("phone");
  const good = ca.attest(phone, { approvalKey, credentialSecretKey: seededRandom("app-attest/credential")(32) });
  const dev = ca.attest(phone, { environment: "development", credentialSecretKey: seededRandom("app-attest/credential")(32) });
  const cdh = attestationClientDataHash(phone, undefined);
  return {
    $comment: COMMENT(
      "App Attest (§9.8): `client_data_hash` is what an iPhone passes to attestKey (every client must match); `attestation` cases check a verifier against a test root (not Apple's) at `now`; `assertion` cases check assertion verification with a stored counter.",
    ),
    app_id: IOS_APP_ID,
    client_data_hash: [
      { name: "with an approval key", identity: phone, approval_key: approvalKey, hex: toHex(attestationClientDataHash(phone, approvalKey)) },
      { name: "without an approval key", identity: phone, approval_key: null, hex: toHex(cdh) },
      { name: "web keys", identity: who("web"), approval_key: null, hex: toHex(attestationClientDataHash(who("web"), undefined)) },
    ],
    root: toB64url(ca.root),
    now: T0,
    attestation: [
      { name: "valid", identity: phone, attestation: good.attestation, allow_development: false, valid: true, credential_public_key: toB64url(good.credentialPublicKey) },
      { name: "another identity", identity: who("other"), attestation: good.attestation, allow_development: false, valid: false },
      { name: "approval key dropped", identity: phone, attestation: { key_id: good.attestation.key_id, object: good.attestation.object }, allow_development: false, valid: false },
      { name: "development, production policy", identity: phone, attestation: dev.attestation, allow_development: false, valid: false },
      { name: "development, development policy", identity: phone, attestation: dev.attestation, allow_development: true, valid: true, credential_public_key: toB64url(dev.credentialPublicKey) },
    ],
    assertion: [
      { name: "counter increases", client_data_hash: toHex(cdh), assertion: toB64url(testAssertion(good.credentialSecretKey, cdh, 3)), last_counter: 2, valid: true, counter: 3 },
      { name: "counter replayed", client_data_hash: toHex(cdh), assertion: toB64url(testAssertion(good.credentialSecretKey, cdh, 2)), last_counter: 2, valid: false },
      { name: "other data", client_data_hash: toHex(attestationClientDataHash(who("other"), undefined)), assertion: toB64url(testAssertion(good.credentialSecretKey, cdh, 3)), last_counter: 0, valid: false },
    ].map((c) => ({ ...c, credential_public_key: toB64url(good.credentialPublicKey) })),
  };
}

export async function buildAll(): Promise<Record<string, unknown>> {
  return {
    "sealed.json": await buildSealed(),
    "live.json": await buildLive(),
    "pairing.json": await buildPairing(),
    "linking.json": await buildLinking(),
    "link-statement.json": await buildStatements(),
    "apns-payload.json": await buildApns(),
    "relay-wire.json": await buildWire(),
    "encoding.json": buildEncoding(),
    "app-attest.json": buildAppAttest(),
  };
}
